name: XCodeBuild

on:
  push:
    branches:
      - main

jobs:
  xcodebuild:
    runs-on: macos-latest
    steps:
      - name: Create Folder
        run: mkdir ios-app
        
      - name: Change Directory
        run: cd ios-app

      - name: FIle
        run: vim main.swift
        
      - name: Generate Project
        run: xcodebuild -project IOSApp.xcodeproj
        
      - name: Change Directory
        run: cd ..
        
      - name: Artifact Upload
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ios-app
        
